# Generated by Django 4.2.4 on 2023-10-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='captcha_text',
            field=models.CharField(max_length=5),
        ),
    ]
