# Generated by Django 4.2.4 on 2023-08-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'ordering': ['-fecha_created'], 'verbose_name': 'imagen', 'verbose_name_plural': 'imagenes'},
        ),
        migrations.AlterModelOptions(
            name='ruta',
            options={'ordering': ['-fecha_realizacion'], 'verbose_name': 'ruta', 'verbose_name_plural': 'rutas'},
        ),
    ]
