# Generated by Django 4.2.4 on 2023-08-28 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_alter_imagen_options_alter_ruta_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('fecha_created', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['-fecha_created'],
            },
        ),
    ]
