# Generated by Django 4.2.4 on 2023-09-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='imagen',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
