# Generated by Django 4.2.4 on 2023-09-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0004_imagen_lat_imagen_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='imagen',
            name='lng',
        ),
    ]
