# Generated by Django 4.2.4 on 2023-10-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0006_ruta_claves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='descripcion',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
