# Generated by Django 4.2.4 on 2023-10-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0007_alter_ruta_descripcion_alter_ruta_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='alt_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ruta',
            name='alt_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ruta',
            name='desnivel_neg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ruta',
            name='desnivel_pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ruta',
            name='distancia_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ruta',
            name='puntos',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tiempo_total',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
