# Generated by Django 4.2.4 on 2023-10-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0009_ruta_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='altitudes',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='distancias',
            field=models.TextField(default='null'),
        ),
    ]
