# Generated by Django 4.2.4 on 2023-10-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0010_ruta_altitudes_ruta_distancias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='claves',
            field=models.CharField(default='null', max_length=400),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='distancia_total',
            field=models.FloatField(default=0),
        ),
    ]
